[package]
name = "paru"
version = "1.11.2"
authors = ["morganamilo <morganamilo@archlinux.org>"]
edition = "2021"

description = "Feature packed AUR helper"
homepage = "http://github.com/Morganamilo/paru"
repository = "http://github.com/Morganamilo/paru"
documentation = "https://docs.rs/paru"
license = "GPL-3.0"
keywords = ["archlinux", "arch", "alpm", "pacman", "aur"]
include = ["src/**/*", "LICENSE", "README.md", "CHANGELOG.md", "help"]


[dependencies]
alpm = "2.2.1"
alpm-utils = "2.0.0"
aur-depends = "3.0.0"
aur-fetch = "0.11.2"
cini = "1.0.0"
pacmanconf = "2.0.0"
raur = "7.0.0"
srcinfo = "1.1.0"


ansi_term = "0.12.1"
anyhow = "1.0.66"
chrono = { version = "0.4.23", default-features = false, features = ["clock"] }
dirs = "4.0.0"
futures = "0.3.25"
globset = "0.4.9"
htmlescape = "0.3.1"
indicatif = "0.17.2"
kuchiki = "0.8.1"
nix = "0.25.0"
reqwest = { version = "0.11.13", features = ["gzip", "socks"] }
rss = { version = "2.0.1", default-features = false }
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.89"
smart-default = "0.6.0"
tempfile = "3.3.0"
term_size = "0.3.2"
tokio = { version = "1.22.0", features = [
    "process",
    "macros",
    "rt-multi-thread",
] }
url = "2.3.1"
env_logger = "0.9.3"
log = "0.4.17"
async-trait = { version = "0.1.58", optional = true }
tr = "0.1.6"
unicode-width = "0.1.10"
regex = "1.7.0"
signal-hook = "0.3.14"
once_cell = "1.16.0"
bitflags = "1.3.2"

[profile.release]
codegen-units = 1
lto = true

[features]
git = ["alpm/git", "alpm-utils/git", "aur-depends/git"]
backtrace = []
generate = ["alpm/generate"]
static = ["alpm/static"]
mock = ["async-trait"]
mock_chroot = ["mock"]

[patch.crates-io]
#alpm = { path = "../alpm.rs/alpm" }
#aur-depends = { path = "../aur-depends" }
#aur-depends = { git = "https://github.com/Morganamilo/aur-depends", rev = "258afa" }
#aur-fetch = { path = "../aur-fetch" }
